<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
    'manager',
    array(
        'action'     => 'create',
        'controller' => 'manager',
        'method' => 'post',
        'class' => 'form-horizontal'
    )
));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();


?>
<script type="text/javascript">
	var $titre = $("input[name$='titre']");
	var $slug = $("input[name$='slug']");
	$titre.on('keyup', function() {
		$slug.val($titre.val().replace(/ /g, "-"));
	})
</script>