<?php

$online = $blog->online ? 'success' : 'danger';

?>

<div class="panel panel-<?= $online; ?>">
              <div class="panel-heading">
                <h3 class="panel-title"><?= $this->escapeHtml($blog->titre); ?></h3>
              </div>
              <div class="panel-body">
                <?php
                	$form = $this->form;
					$form->setAttribute('action', $this->url(
					    'manager',
					    array(
					        'action'     => 'edit',
					        'controller' => 'manager',
					        'id' => $blog->id,
					        'method' => 'post',
					        'class' => 'form-horizontal'
					    )
					));
					$form->prepare();
					 
					echo $this->form()->openTag($form);
					echo $this->formCollection($form);
					echo $this->form()->closeTag();

                ?>
              </div>
</div>