
    <?php foreach ($this->flashMessenger()->getMessages() as $msg) : ?>
    	<?php echo $msg; ?>
    <?php endforeach; ?>

<div class="alert alert-info">
 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
 <h4>Welcome !</h4>
 <p>Welcome on your blog manager  <a class="alert-link"><?php echo $this->escapeHtml($this->zfcUserIdentity()->getEmail()); ?></a> !<br>
 	You now can use this manager to create / manage the content of your blog(s).
 </p>
</div>

<div class="row">
	<div class="col-md-8">
		<h4>Configuration</h4>
		<div id="container">

		</div>
	</div>
	<div class="col-md-4">
			<h4 class="example-title">My Blogs</h4>
            <div class="list-group">
              <?php 
              	foreach($blog as $value):
              		$color = $value->online ? 'badge-success' : 'badge-danger';
              		$state = $value->online ? 'Online' : 'Offline';
              		?>
              			
              			<a href="#" class="list-group-item" data-id="<?= $value->id; ?>"><span class="badge <?= $color; ?>"><?= $state; ?></span><?= $this->escapeHtml($value->titre); ?></a>
              		<?php
              	endforeach;
              ?>
            </div>
    </div>
</div>

<script type="text/javascript">
	$(".list-group-item").on("click", function() {
		var id = $(this).context.dataset.id;
		$.get("/manager/edit/" + id, function(res) {
			$("#container").html('').slideUp().append(res).slideDown()
		});
	});
</script>